name: plan
inputs:
  tf_component:
    description: 'terraform component directory name'
    required: true
  env:
    description: 'AWS environment'
    required: true
  region:
    description: 'AWS region'
    default: 'eu-west-1'
runs:
  using: "composite"
  steps:
    - run: |
        echo "Running terraform plan in ${{ inputs.tf_component }}/terraform"
        echo "cd ${{ inputs.tf_component }}/terraform"
        echo "mkdir -p terraform-plans"
        echo "terraform init -input=false -backend-config=${{ inputs.tf_component }}/environments/${{ inputs.env }}/${{ inputs.region }}/file.tfvars"
        echo "terraform plan -input=false -out=terraform-plans/${{ inputs.tf_component }}.plan -var-file=${{ inputs.tf_component }}/environments/${{ inputs.env }}/${{ inputs.region }}/file.tfvars"
      shell: sh
