name: organizations

env:
  TF_COMPONENT: 'organizations'

defaults:
  run:
    shell: sh

on: 
  push:
    paths:
      - 'organizations/**'
      - '!organizations/README.md'
      - '.github/workflows/organizations.yaml'
      - '.github/actions/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check format of terraform code
        uses: ./.github/actions/fmt
        with:
          tf_component: ${TF_COMPONENT}
      - name: Check validity of terraform code with dev config
        uses: ./.github/actions/validate
        with:
          tf_component: ${TF_COMPONENT}
          env: msaitz
  plan:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run terraform plan
        uses: ./.github/actions/plan
        with:
          tf_component: ${TF_COMPONENT}
          env: msaitz
      - name: echo file
        run: |
          mkdir plan-outputs
          echo pollo > plan-outputs/plan.out
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: msaitz-plan-file
          path: plan-outputs/plan.out
  apply:
    needs: plan
    environment:
      name: prod
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download plan
        uses: actions/download-artifact@v2
        with:
          name: msaitz-plan-file
          path: plan-outputs
      - name: Run terraform plan
        uses: ./.github/actions/apply
        with:
          tf_component: ${TF_COMPONENT}
          env: msaitz
